import type { Trip } from "./trip-data";

export function exportTripPDF(trip: Trip) {
  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${trip.title} — Voyagr</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, sans-serif; color: #111; padding: 40px; max-width: 700px; margin: auto; }
    header { border-bottom: 2px solid #111; padding-bottom: 20px; margin-bottom: 28px; }
    header h1 { font-size: 28px; font-weight: 700; letter-spacing: -0.5px; }
    header p { color: #555; margin-top: 4px; font-size: 14px; }
    .badge { display: inline-block; background: #111; color: #fff; border-radius: 99px; padding: 3px 12px; font-size: 12px; font-weight: 600; margin-top: 10px; }
    .day { margin-bottom: 28px; }
    .day-title { font-size: 16px; font-weight: 700; padding: 8px 0; border-bottom: 1px solid #eee; margin-bottom: 12px; }
    .day-num { color: #999; font-weight: 400; margin-right: 8px; }
    .place { display: flex; align-items: flex-start; gap: 12px; padding: 10px 0; border-bottom: 1px solid #f0f0f0; }
    .place:last-child { border-bottom: none; }
    .emoji { font-size: 20px; width: 32px; text-align: center; }
    .place-info h3 { font-size: 14px; font-weight: 600; }
    .place-info p { font-size: 12px; color: #777; margin-top: 2px; }
    .time { margin-left: auto; font-size: 12px; color: #999; white-space: nowrap; padding-left: 12px; }
    footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #eee; font-size: 11px; color: #aaa; text-align: center; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <header>
    <h1>${trip.title}</h1>
    <p>${trip.destination} · ${trip.dates}</p>
    <span class="badge">Voyagr Itinerary</span>
  </header>
  ${trip.days.map((day) => `
    <div class="day">
      <div class="day-title"><span class="day-num">Day ${day.day}</span>${day.title}</div>
      ${day.places.map((p) => `
        <div class="place">
          <span class="emoji">${p.emoji}</span>
          <div class="place-info">
            <h3>${p.name}</h3>
            <p>${p.city} · ${p.tag}</p>
          </div>
          <span class="time">${p.time}</span>
        </div>
      `).join("")}
    </div>
  `).join("")}
  <footer>Generated by Voyagr · ${new Date().toLocaleDateString("en", { dateStyle: "long" })}</footer>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => { win.print(); }, 400);
}
